# Generated by Django 2.1.7 on 2019-04-10 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testing',
        ),
    ]
