# Generated by Django 2.1.7 on 2019-04-10 05:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0002_delete_testing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('officecode', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('officename', models.CharField(max_length=50)),
                ('attribution', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organizationcode', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('organizationname', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('datejoined', models.DateTimeField(default=django.utils.timezone.now)),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('servicecode', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('servicename', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('premium', models.CharField(max_length=50)),
                ('allocation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('subscriptiontypecode', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('subscriptiontypename', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('middlename', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=50)),
                ('employername', models.CharField(max_length=50)),
            ],
        ),
    ]
