# Generated by Django 2.1.7 on 2019-04-11 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_office_organization_service_subscriptiontype_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('subscriberID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('requestdate', models.DateField()),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('motifofcancellation', models.TextField()),
                ('beneficiaryID', models.CharField(max_length=50)),
                ('servicecode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Service')),
                ('subscriptiontypecode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.SubscriptionType')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.UserInfo')),
            ],
        ),
    ]
