# Generated by Django 2.1.7 on 2019-04-11 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferredSubscription',
            fields=[
                ('transferID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('transferfrom', models.CharField(max_length=50)),
                ('transferto', models.CharField(max_length=50)),
                ('requestdate', models.DateField()),
                ('transferdate', models.DateField()),
                ('subscriberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Subscriber')),
            ],
        ),
    ]
