# Generated by Django 2.1.7 on 2019-04-12 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_organizationmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='beneficiaryID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Subscriber'),
        ),
    ]
