# Generated by Django 2.1.7 on 2019-04-12 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20190412_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='attribution',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='beneficiaryID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Subscriber'),
        ),
    ]
