# Generated by Django 2.1.7 on 2019-04-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20190412_0722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationmember',
            old_name='isdelegate',
            new_name='is_delegate',
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
